service: toplegal-assignment
	
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  profile: default
  memorySize: 256
  stage: dev
  environment:
    NODE_ENV: dev
    JWT_KEY: somesecret
  httpApi:
    cors: true
 

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

custom:
  dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      migrate: true
      seed: true
      convertEmptyValues: true

resources:
  Resources:
    contractsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: contracts
        AttributeDefinitions:
          - AttributeName: contractID
            AttributeType: S
        KeySchema:
          - AttributeName: contractID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: UserEmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1